### ISSUE TITLE
Names of created images

### ISSUE THREAD

**Issue by psychemedia** [leighmcculloch/vagrant-docker-compose#7] opened 2015-07-24 19:17 UTC
I'm using vagrant-docker-compose to create a set of images within a VM using one `Vagrantfile` & `docker-compose.yml` file, bundling that VM and then launching containers within it using another `Vagrantfile` & `docker-compose.yml` file.

The original images (which are built) are automatically named as eg `vagrant_foo` and `vagrant_bar` based on the name given in the YAML file. These images exist in the VM, eg as per:

```
$docker images

REPOSITORY                   TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
vagrant_ipynb                latest              1bb94ebe6e38        3 hours ago         3.138 GB
vagrant_mongo                latest              51be69974278        3 hours ago         278 MB
ipython/scipystack           latest              720dc652b731        24 hours ago        2.857 GB
```

If I set eg `image: vagrant_mongo` as the name of an image in a new `docker-compose.yml` file, I get the error `Error: image library/vagrant_mongo:latest not found`.

If I set the name as `./vagrant_mongo ` I get `HTTPS endpoint unresponsive and insecure mode isn't enabled.`.

So how do I address the created images? Is there anyway I can configure `vagrant-docker-compose` to get names of the form `myimage/vagrant_mongo` and then try to load those

**Comment by psychemedia** [comment] 2015-07-25 13:25
When rerunning a `vagrant` script, I keeping getting an error on one of my containers (quite a large one) getting ripped down and replaced:

```
Recreating vagrant_devpostgresdata_1...
Recreating vagrant_devpostgres_1...
Recreating f9ceb317c4_f9ceb317c4_f9ceb317c4_vagrant_ipynb_1...
```

Each time I reload the machine, I get another level of nesting on the `ipynb` container which then causes a `Duplicate bind mount /notebooks` error, presumably as multiple differently named containers try to mount the /notebooks` directory?

Here's the relevant `Dockerfile':

```
devpostgresdata:
    command: echo created
    image: busybox
    volumes: 
        - /var/lib/postgresql/data
 
devpostgres:
    environment:
        - POSTGRES_PASSWORD=PGPass
    image: postgres
    ports:
        - "5432:5432"
    volumes_from:
        - devpostgresdata
 
ipynb:
  image: psychemedia/tm351_scipystacknserver:tm351d3test
  ports:
    - "8888:8888"
  volumes:
    - ./notebooks/:/notebooks/
  links:
    - devpostgres:postgres
    - mongo:mongo
    - openrefine:openrefine
  privileged: true
```

and the Vagrantfile:

```
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider :virtualbox do |virtualbox|
  	virtualbox.memory = 1024
  end
  
  config.vm.network(:forwarded_port, guest: 8888, host: 8351,auto_correct: true)
  
  #Check that necessary host directories are in place
  config.vm.provision :shell, :inline => <<-SH
    mkdir -p notebooks
  SH

  #If you need to get into a container:
  # vagrant ssh
  # docker exec -it CONTAINERNAME bash
  
  config.vm.provision :docker_compose, yml: "/vagrant/docker-compose.yml", run: "always"
end
```

**Comment by leighmcculloch** [comment] 2015-07-29 05:41
@psychemedia these look like they might be separate issues, lets deal with the first one here. docker-compose will use the image name and the project name to make the container names for the docker images it creates. When you reload the images using your second docker-compose.yml you probably want to make sure you set the project name and image names separately again, rather than including the project name in the image name.

The project name by default will be the directory that docker-compose runs in, and this by default is `/vagrant` which means the project name is `vagrant`.

Can you try changing the image names in your second docker-compose.yml to `mongo` and `ipynb` so they don't have the project prefix, because the second docker-compose.yml will re-add the project anyway.

Give that a go, there might be other things that docker-compose is doing automatically that might be preventing you from doing what you want to do if it stores intermediary files elsewhere.

**Comment by psychemedia** [comment] 2015-07-29 08:41
@leighmcculloch I was using the simple form of the name (mongo, ipynb) in the second vagrant script. The `ipynb` container was the only one getting misnamed; it's quite a large container, with a mount on host, also running in privileged mode. It was also the last container mentioned in the yml file. (I've been starting to develop superstitious beliefs about possible causes! Too much late night working...)

**Comment by leighmcculloch** [comment] 2015-07-29 14:12
I'm not sure what to suggest then, if you were only having issues with one of the containers, but were doing the same thing with both then maybe it was a configuration issue caused by late-night working :). If that's the case would you like to close the issue, retry it not-late-at-night and see if we have a winner?

**Comment by leighmcculloch** [comment] 2015-11-28 21:28
@psychemedia I'm gong to close, please reopen if you have ideas on how to move forward on this and what was happening.

**Closed by leighmcculloch** 2015-11-28 21:28 UTC
