### ISSUE TITLE
Context path with multiple docker-compose files

### ISSUE THREAD

**Issue by FlaTutu** [leighmcculloch/vagrant-docker-compose#35] opened 2016-08-11 18:19 UTC
I have an issue with this plugin.
I have multiple docker-compose files, and any of them have Dockerfile pathes in it. Furthermore, there are external links between them.

It seems that the first path declared in yml array will be the current path in context for all building and running docker-compose files.
I have two problems :
- First one, the relative path to the Dockerfile will always start to the first yml file declared, so docker-compose can't find it. I solved temporarily the problem by setting absolute path, but this path isn't relevant outside my vagrant.
- Second one, as docker-compose name built images with the parent directory of the docker-compose, all my built images will have wrong name, and all my external links are wrong too.

Sorry for my english, I hope that is understandable.

**Comment by leighmcculloch** [comment] 2016-09-04 03:16
Let me echo back to make sure I understand the two issues:
1. The working directory for where to look for Dockerfiles is based off the first YML file, but should be configurable?
2. The names of the images built ues the parent directory, but should be configurable?

**Comment by T3N4K4** [comment] 2020-06-09 15:11
@leighmcculloch 
I don't know of the challenges the OP had, but I can confirm issue nr. 1 not only for Dockerfiles, but .env too.

```
==> default: Couldn't find env file: /home/vagrant/projects/project1/.docker/wordpress/.env.local
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

 /usr/local/bin/docker-compose-1.24.1  -f "/home/vagrant/projects/project1/docker-compose.yml" -f "/home/vagrant/projects/project1/docker-compose.local.yml" -f "/home/vagrant/projects/project2/docker-compose.yml" -f "/home/vagrant/projects/project2/docker-compose.local.yml" rm --force

Stdout from the command:
Stderr from the command:

Couldn't find env file: /home/vagrant/projects/project1/.docker/wordpress/.env.local
```

The path `.docker/wordpress/.env.local` exists in project2.

**Comment by leighmcculloch** [comment] 2020-06-09 15:24
Thanks for sharing an example. What do you think should change to make this work? Instead of passing each docker-compose file to a single call of docker-compose should each file be a separate execution of docker-compose?

**Comment by T3N4K4** [comment] 2020-06-09 15:31
Thats a good question ;-).

I am not deep enough inside docker-compose to tell if the call below 

`/usr/local/bin/docker-compose-1.24.1 -f "/home/vagrant/projects/project1/docker-compose.yml" -f "/home/vagrant/projects/project1/docker-compose.local.yml"`

would be the same as

`/usr/local/bin/docker-compose-1.24.1 -f "/home/vagrant/projects/project1/docker-compose.yml"`
`/usr/local/bin/docker-compose-1.24.1 -f "/home/vagrant/projects/project1/docker-compose.local.yml"`

If this is the case is it only a matter of more memory consumption of the docker-compose executable? Or are we missing some other constraints which may occur?

**Comment by leighmcculloch** [comment] 2020-06-09 15:58
What if you replace your one:
```
config.vm.provision :docker_compose, yml: ["project1/docker-compose.yml", "project2/docker-compose.yml"], run: "always"
```
With multiple:
```
config.vm.provision :docker_compose, yml: "project1/docker-compose.yml", run: "always"
config.vm.provision :docker_compose, yml: "project2/docker-compose.yml", run: "always"
```
Does that resolve the issue?

**Comment by T3N4K4** [comment] 2020-06-09 19:18
That did the trick. I just checked it.
Since I am using only docker-compose.yml files I am not noticing any naming issues on the containers.

Thank you :-).

**Comment by leighmcculloch** [comment] 2020-06-10 02:12
Excellent. I'm going to close the issue. Anyone is welcome to reopen the issue if this is not addressed.

**Closed by leighmcculloch** 2020-06-10 02:12 UTC
Labels: needs information
