### ISSUE TITLE
".env" not taken into account

### ISSUE THREAD

**Issue by mbrodala** [leighmcculloch/vagrant-docker-compose#52] opened 2018-10-10 10:42 UTC
We noticed that our [local `.env` file](https://docs.docker.com/compose/environment-variables/#the-env-file) is not used by `docker-compose` which is used to set various options.

I assume that's becaues `docker-compose` is executed in the default login directory (e.g. `/home/vagrant`) instead of the directory of the `.env` file. In our case that would be `/vagrant` where the Compose files are located too.

Would it be possible to add an option to switch the working directory for the `docker-compose` command?

This could be related to #43.

**Comment by mbrodala** [comment] 2018-10-10 13:34
Everything is toplevel:

```
.env
docker-compose.yml
...
```

The `Vagrantfile` then looks accordingly:

```rb
  config.vm.provision "app",
    type: "docker_compose",
    compose_version: "1.22.0",
    yml: "/vagrant/docker-compose.yml",
    env: {
      # I'd like to get rid of this
    },
    run: "always"
```

I also noticed that `yml` always needs to use absolute paths which would be obsolete if one could set a working directory here.

**Comment by leighmcculloch** [comment] 2018-10-10 15:21
🤔 That's a good point. If we supported a working directory it would make working with this a lot easier. @mbrodala Are you up for taking a stab at adding support for this and opening a PR?

**Comment by mbrodala** [comment] 2018-10-11 09:09
I'd love to but unfortunately I have limited time ATM. :-/

**Comment by mbrodala** [comment] 2018-10-22 09:12
As a workaround we now use a setup like this:

```ruby
  config.vm.provision :docker_compose,
    compose_version: "1.22.0"

  config.vm.provision "app",
    type: "shell",
    keep_color: true,
    privileged: false,
    run: "always",
    inline: <<-SCRIPT
      cd /vagrant
      docker-compose up --detach
    SCRIPT
```

This has many advantages:

1. The `.env` file is loaded by Docker Compose since we switch the working directory.
2. We can execute as regular user instead of `root`.
3. Output colors can be rendered as is.

**Comment by leighmcculloch** [comment] 2019-10-25 04:16
This is a duplicate of #43, let's track there.

**Closed by leighmcculloch** 2019-10-25 04:16 UTC
Labels: Hacktoberfest, enhancement, good first contribution, needs pr
